name: check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    permissions:
      checks: write
    uses: cxreiff/github_workflows/.github/workflows/rust_check.yml@main
    with:
      msrv: 1.76.0
